spring:
  application:
    name: user-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: spring_boot_transaction
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-cloud-ecosystem

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    notification_circuit_breaker: # Must match the name in @CircuitBreaker
      registerHealthIndicator: true
      slidingWindowSize: 5
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


logging:
  level:
#    root: DEBUG
    org:
      springframework:
        security: DEBUG