spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-cloud-ecosystem

server:
  port: 3000

logging:
  level:
    org:
      springframework:
        security: DEBUG